### ISSUE TITLE
Why does solang not recognize msg and block?

### ISSUE THREAD

**Issue by q871795224** [hyperledger-labs/solang#219]
![image](https://user-images.githubusercontent.com/33190881/86523353-db808f80-be9d-11ea-8b2d-429a320df6f5.png)
As shown in the picture。
The corresponding code is `creator = msg.sender;``return block.number;``if (msg.sender == creator)`

**Comment by seanyoung** [comment]
You are right, this is not implemented yet. However, I'm currently implementing these features the current milestone which is due the 25th of July: https://github.com/hyperledger-labs/solang/milestone/3

**Comment by seanyoung** [comment]
Work is underway here: https://github.com/hyperledger-labs/solang/pull/220

**Comment by seanyoung** [comment]
This should be fixed now.
