### ISSUE TITLE
What Solidity version is supported ?

### ISSUE THREAD

**Issue by SvenMeyer** [hyperledger-labs/solang#264]
Where is information what Solidity version is supported ?
v0.5 , v0.6 , v0.7 ?

**Comment by seanyoung** [comment]
The aim to be current with the latest version of Solidity (0.7), however it falls short in a few areas:

- function modifiers (should be implemented soon)
- function types
- immutables
- there are probably some smaller problems

Please raise an issue for anything specific you find.

**Comment by seanyoung** [comment]
See https://solang.readthedocs.io/en/latest/status.html for a list of features.

function modifiers have now been implemented.
