### ISSUE TITLE
Is the `ethereum.memory` in the import section needed when I use `ewasm` backend?

### ISSUE THREAD

**Issue by hydai** [hyperledger-labs/solang#266]
Hi,
I am trying to build a simple contract with solang v0.1.3.
Here is the contract in solidity:

```solidity
contract Token {
        uint256 private totalSupply;
        mapping(address => uint256) public balances;

        function add(uint256 a, uint256 b) internal pure returns (uint256) {
                uint256 c = a + b;
                require(c >= a, "SafeMath: addition overflow");

                return c;
        }

        function sub(uint256 a, uint256 b) internal pure returns (uint256) {
                require(b <= a, "SafeMath: subtraction overflow");
                uint256 c = a - b;

                return c;
        }

        constructor() public {
                totalSupply = 100000000;
                balances[msg.sender] = totalSupply;
        }

        function balanceOf(address account) view public returns (uint256) {
                return balances[account];
        }

        function transfer(address to, uint256 amount) public returns (bool) {
                balances[msg.sender] = sub(balances[msg.sender], amount);
                balances[to] = add(balances[to], amount);
                return true;
        }
}
```

Compile command:

```bash
./solang_linux --target ewasm ./Token.sol
```

I found that there is a special import statement `(import "ethereum" "memory" (memory (;0;) 2 2))` in the output wasm file.
After I check the ewasm spec, it looks like there is no `ethereum.memory` for importing in EEI.
I would like to know if this import statement is also needed on ewasm runtime?

In addition, [Ethereum Contract Interface](https://ewasm.readthedocs.io/en/mkdocs/contract_interface/) requires `export memory`, but this is also missed in the output wasm file.

**Comment by seanyoung** [comment]
@hydai thanks for your bug report. Solang has only been testing with [https://github.com/hyperledger/burrow/](Burrow) so far, so there a bond to be issues like these.

This is easy to fix up, I'll fix it today.

**Comment by seanyoung** [comment]
Please let me know if this is fixed now.

Please let me know about any issues you find, thanks!

**Comment by hydai** [comment]
Thanks a lot. @seanyoung 👍 

The above issue is resolved.


Actually, we are trying to use a ewasm-compatible runtime, [SSVM](https://github.com/second-state/ssvm), to do some benchmarks. The SSVM also provides [a rust binding for EVMC](https://github.com/second-state/rust-ssvm).

We will open a new issue if we encounter another bug when running benchmarks. Thanks again.
