### ISSUE TITLE
Version with latest scale-info compatible metadata

### ISSUE THREAD

**Issue by jacogr** [hyperledger-labs/solang#297]
This is a support query to help others just find their bearings...

In the polkadot-js/docs we have been referring to ink! 3 a lot to indicate the latest version wit the new metadata. Solang also supports it fully, but it seems the docs are skewed there since it doesn't reflect that at all or at least doesn't provide the required pointers.

So would like o update the offending references, an example being here https://polkadot.js.org/docs/api-contract/FAQ#my-abi-cannot-be-parsed - which version should I refer to for compat reasons? (The apps UI is slightly better, but just generally refers to a "newer version of solang")

**Comment by seanyoung** [comment]
There is no tagged released yet which supports the new metadata, this is only on master. I'm hoping to do a release soon. On the problems I'm having is that the new metadata breaks things for plasm: https://github.com/staketechnologies/Plasm/issues/245

**Comment by seanyoung** [comment]
There is now a release v0.1.5 which is compatible with the new substrate 2.0 metadata.

**Comment by jacogr** [comment]
Thank you, yes, saw it come in, updated the UI with a reference 15 mins later. Will close this.
