### ISSUE TITLE
For some previous solidity complier version

### ISSUE THREAD

**Issue by KunPengRen** [hyperledger-labs/solang#306]
Can this tool support the previous solidity version, like v.4.24 for solidity?

**Comment by seanyoung** [comment]
There are many changes in the language between solidity versions. It would be good if solang could switch between solidity versions. This would require some big changes to sema.

Unfortunately I do not have the time to implement this. However, I'm very much open to contributions for this.

**Comment by seanyoung** [comment]
It occurred to me that more can be done to solve this problem.

@KunPengRen it would be more useful to know what specific compilation problems you are having.

**Comment by seanyoung** [comment]
I have made some modifications so previous versions of solidity also compile. Please let me know if there are specific issues you are having.

**Comment by KunPengRen** [comment]
Thanks! That's great, I will test later.
