### ISSUE TITLE
LLVM Issues

### ISSUE THREAD

**Issue by YameenMalik** [hyperledger-labs/solang#314]
Trying to generate .wasm file for [this](https://github.com/Synthetixio/synthetix/blob/develop/contracts/AddressResolver.sol) contract, getting this error. Couldn't find anything to read about it on google so opening the issue here. Any assistance would be much appreciated. 

```
AddressResolver.sol:50:33-39: warning: ‘public’: visibility for constructors is ignored
AddressResolver.sol:205:33-39: warning: ‘public’: visibility for constructors is ignored
solang: llvm/lib/IR/Instructions.cpp:2334: static llvm::BinaryOperator* llvm::BinaryOperator::Create(llvm::Instruction::BinaryOps, llvm::Value*, llvm::Value*, const llvm::Twine&, llvm::Instruction*): Assertion `S1->getType() == S2->getType() && "Cannot create binary operator with two operands of differing type!"' failed.
Aborted (core dumped)
```

**Comment by YameenMalik** [comment]
I linked the incorrect contract unfortunately sorry about that. I resolved the import path issues by flattening the contract. You can find the flattened contract over [here](https://github.com/dtradeorg/dtrade-contracts/blob/main/contracts/build/flattened/AddressResolver.sol). Thanks

**Comment by seanyoung** [comment]
I've been down a rabbit hole trying to fixing the imports

**Comment by seanyoung** [comment]
@YameenMalik please let me know if you come across any issues with the latest version; it should be fixed, including the import path issues.

**Comment by TriplEight** [comment]
I just had something else trying to compile on the mentioned commit:
```
   Compiling tempfile v3.1.0
error: No suitable version of LLVM was found system-wide or pointed
       to by LLVM_SYS_100_PREFIX.

       Consider using `llvmenv` to compile an appropriate copy of LLVM, and
       refer to the llvm-sys documentation for more information.

       llvm-sys: https://crates.io/crates/llvm-sys
       llvmenv: https://crates.io/crates/llvmenv
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/llvm-sys-100.2.0/src/lib.rs:483:1
    |
483 | / std::compile_error!(concat!(
484 | |       "No suitable version of LLVM was found system-wide or pointed
485 | |        to by LLVM_SYS_", env!("CARGO_PKG_VERSION_MAJOR"), "_PREFIX.
486 | |
...   |
490 | |        llvm-sys: https://crates.io/crates/llvm-sys
491 | |        llvmenv: https://crates.io/crates/llvmenv"));
    | |____________________________________________________^

error: aborting due to previous error

error: could not compile `llvm-sys`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `solang v0.1.5 (https://github.com/hyperledger-labs/solang?rev=0b77c1e8ae250e02327b86681c63d1a6cf72d70c#0b77c1e8)`, intermediate artifacts can be found at `/tmp/cargo-installr66Saf`

```

**Comment by seanyoung** [comment]
LLVM can't be found. See https://solang.readthedocs.io/en/latest/installing.html#installing-the-llvm-libraries for how to install llvm. It's best to use the llvm version based of our tree, it has some fixes in it.

Make sure that `llvm-config --version` returns the correct version before running cargo again.

This morning I've made another fix which is relevant for compiling synthetix: https://github.com/hyperledger-labs/solang/pull/331, so please make sure to pull the latest master
