### ISSUE TITLE
Compiler Should Output .contract Bundle

### ISSUE THREAD

**Issue by bitsanity** [hyperledger-labs/solang#344]
[Using Solang with Substrate](https://solang.readthedocs.io/en/latest/running.html#using-solang-with-substrate)  indicates that compiling a solidity file should output a `.contract` file containing wasm and json.

The Substrate UIs seem to prefer uploading a `.contract` file. While they do allow uploading `.wasm` and `.json` separately, the UI doesn't seem to handle multiple wasms and multiple jsons.

Let there be two contracts, ContractA and ContractB in one solidity source file.

`$ solang_linux --target substrate MySource.sol`

or simply (because substrate is the default):

`$ solang_linux MySource.sol`

Files produced:
- ContractA.wasm
- ContractA.json
- ContractB.wasm
- ContractB.json

Files expected:
- MySource.contract

I'd like to advise which exact version but it looks like its not defined...

    $ solang_linux --version
    solang version

**Comment by seanyoung** [comment]
A fix for this issue was committed yesterday: https://github.com/hyperledger-labs/solang/commit/66ab8d013f7878491f9ef9ecb54eda2449ad8696

You can test this by using the latest docker image or using the debug artifacts generated here https://github.com/hyperledger-labs/solang/actions/runs/438060355
