### ISSUE TITLE
does solong support EVM script? or contract call?

### ISSUE THREAD

**Issue by GalaIO** [hyperledger-labs/solang#365]
like this exec EVM script
https://github.com/aragon/aragon-apps/blob/631048d54b9cc71058abb8bd7c17f6738755d950/apps/voting/contracts/Voting.sol#L355

or call erc20 transferFrom
https://github.com/aragon/aragon-apps/blob/631048d54b9cc71058abb8bd7c17f6738755d950/apps/token-manager/contracts/TokenManager.sol#L318

**Comment by seanyoung** [comment]
@GalaIO this evm script is something which is special to AragonOS, no special support is  in the solidity compiler, I think. See https://github.com/aragon/aragonOS/blob/next/contracts/evmscript/EVMScriptRunner.sol

In fact we could add a special feature in Solang if this is needed. What are you trying to achieve?

On the second point, cross contract calls are fully supported.
