### ISSUE TITLE
Does Solang support generating LLVM bitcode?

### ISSUE THREAD

**Issue by taquangtrung** [hyperledger-labs/solang#395]
Hi,

Does your tool support compile Solidity to LLVM bitcode?
I read your documentation and couldn't find that information.

Thank you for taking a look at this issue.

**Comment by seanyoung** [comment]
@taquangtrung solang can generate llvm ir in binary (bitcode) or text format. Run solang with the following option:

```
solang --emit llvm-bc foo.sol -v
```

If you would like the text version:
```
solang --emit llvm-ir foo.sol -v
```
Does this help? What are you trying to achieve? Thanks

**Comment by taquangtrung** [comment]
Thank you very much! It works for me when run directly with the binary file.
I'm trying to build a static analyzer for Solidity based on LLVM bitcode.

Btw, when running using Docker, I got this error:
```
docker run hyperledgerlabs/solang /usr/bin/solang --emit llvm-ir ../solidity-examples/storage.sol -v

info: Solang version v0.1.6-87-g90b46a4
solang: error: failed to read file ‘/usr/bin/solang’: stream did not contain valid UTF-8
/usr/bin/solang: error: no valid contracts found
```

Could you advise if I run it correctly?

**Comment by seanyoung** [comment]
So when you run solang in a docker container, you don't need to specify `/usr/bin/solang`  as solang is already specified as the entrypoint. So, here solang is trying to itself as a source file and decides it's not valid text.

The second issue is that accessing files in a docker container is a bit awkward. The container does not have access to your files, so you need to some mapping to make it possible.

This should work (I think)
```
docker run -v  ../solidity-examples:/sources hyperledgerlabs/solang --emit llvm-ir /sources/storage.sol  -o /sources/ -v
```

```

**Comment by taquangtrung** [comment]
Oh right! Thank you very much for pointing out the issue with Docker. I wasn't careful at this point.

**Comment by seanyoung** [comment]
Is it ok to close this issue or is there anything else?

**Comment by taquangtrung** [comment]
Thanks alot! I will close it.
