### ISSUE TITLE
Some errors when running llvm-opt with the bitcode generated by Solang

### ISSUE THREAD

**Issue by taquangtrung** [hyperledger-labs/solang#396]
Hi,

I tested the following simple contract with Solang to generate LLVM bitcode.

```
pragma solidity ^0.4.0;

contract SimpleStorage {
  uint storedData;

  function set(uint x) public {
    storedData = x;
  }

  function get() public view returns (uint) {
    return storedData;
  }
}
```

When running llvm-opt with the generated bitcode, there was an error like below. 

```
opt -mem2reg SimpleStorage.bc

Global is external, but doesn't have external or weak linkage!
void (i64, i8*, i32*)* @seal_weight_to_fee
/usr/bin/opt: SimpleStorage.bc: error: input module is broken!
```

The IR corresponding to the above error is:

```
declare internal void @seal_weight_to_fee(i64, i8*, i32*)
```

Is it the intended behavior of Solang to not introduce keywords mentioned by llvm-opt?

Btw, thank you for the great tool. So far, it's the best compiler from Solidity to LLVM, AFAIK.

**Comment by seanyoung** [comment]
This is obviously broken, I'll see if I can fix it.

In the mean time, you can use `--emit llvm-ir` rather than `--emit llvm-bc` and simply remove the offending line in the text format.

**Comment by seanyoung** [comment]
Should be fixed now. Note that it takes a few hours for the docker images to update

**Comment by seanyoung** [comment]
Is it ok to close this issue or is there anything else?

**Comment by taquangtrung** [comment]
Yes, it worked perfectly! Thank you very much!

**Comment by seanyoung** [comment]
I'm not sure exactly what you're doing, but just in case: actually I haven't done a particularly good job of selecting the passes that solang runs when compiling a contract. If you find any more that should be added, please let me know or open a PR. (see pass manager in src/emit/mod.rs)

**Comment by taquangtrung** [comment]
Thanks for the kind notice! I will definitely discuss with you when I face any difficulties with Solang
