### ISSUE TITLE
Mac M1 linking with `cc` failed

### ISSUE THREAD

**Issue by VadneyK** [hyperledger-labs/solang#421]
trying to install llvm to install solang binary for rust/substrate.

Downloaded the tar file from https://solang.readthedocs.io/en/latest/installing.html#installing-llvm-on-ubuntu
then: 
![Screen Shot 2021-05-26 at 8 42 28 AM](https://user-images.githubusercontent.com/57117207/119690177-4f04f580-bdfe-11eb-86cb-1f6d33d6999d.png)

as instructed but then I get:

![Screen Shot 2021-05-26 at 8 42 58 AM](https://user-images.githubusercontent.com/57117207/119690277-60e69880-bdfe-11eb-97cd-af5984b2d11d.png)

why does the cargo install command think I have another file named solang somewhere? That's what the error message seems to mean as of here: https://stackoverflow.com/questions/28124221/error-linking-with-cc-failed-exit-code-1

Here is my config:
macOS bigsur ver 11.2.3 M1 chip

![Screen Shot 2021-05-26 at 8 45 42 AM](https://user-images.githubusercontent.com/57117207/119690690-c2a70280-bdfe-11eb-994e-8f90b974c851.png)

**Comment by seanyoung** [comment]
The llvm build you are using is built for intel, not m1. Unfortunately there is no pre-build version of llvm available for m1 yet. 

You can build your own using these instructions https://solang.readthedocs.io/en/latest/installing.html#building-llvm-from-source

**Comment by VadneyK** [comment]
thanks! that almost worked. Does this error mean I have to make a /include folder and move llvm to be there? I have not touched any files after git cloning.

![Screen Shot 2021-05-26 at 8 32 03 PM](https://user-images.githubusercontent.com/57117207/119761863-6fb26700-be61-11eb-8560-6b27649cdc29.png)

**Comment by seanyoung** [comment]
This looks like `CMAKE_INSTALL_PREFIX` was not set properly. Please can you re-run the first cmake with something like `-DCMAKE_INSTALL_PREFIX=/Users/kentarovadney/llvm11` or so, thanks.

**Comment by VadneyK** [comment]
Thanks!

I did
`
cmake -G Ninja -DLLVM_ENABLE_ASSERTIONS=On '-DLLVM_ENABLE_PROJECTS=clang;lld'  \
        -DLLVM_ENABLE_TERMINFO=Off -DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_INSTALL_PREFIX=/Users/kentarovadney/llvm11 -B build llvm
`
and 
`
PATH=/Users/kentarovadney/llvm11/bin:$PATH
`

then cargo install solang

and it worked!
