### ISSUE TITLE
docker image - error: could not compile `regex-syntax`

### ISSUE THREAD

**Issue by VadneyK** [hyperledger-labs/solang#422]
I try to run a docker image with solang here, but I get error: could not compile `regex-syntax`

![Screen Shot 2021-05-26 at 8 53 13 AM](https://user-images.githubusercontent.com/57117207/119691895-cf782600-bdff-11eb-9464-a3ad7dc35d7f.png)

where do I insert the --verbose to get the full error message?
why is regex-syntax not compiling?

config:
macOS bigsur ver11.2.3 M1 chip
![Screen Shot 2021-05-26 at 8 52 07 AM](https://user-images.githubusercontent.com/57117207/119691709-a8b9ef80-bdff-11eb-9cf7-2245ef25aa40.png)

**Comment by seanyoung** [comment]
docker should use the rustc from the docker image, not the one on the mac itself. Would you mind trying the following please

- `git clean -fdx` so any temporary files are gone
- `docker image pull hyperledgerlabs/solang:ci` to make sure you're using the latest solang ci image
- `docker image pull  ubuntu:18.04`

And then try `docker image build .` again. Thanks

**Comment by VadneyK** [comment]
Thanks! I just did all of those things but i still get the same error.
Also how do I configure which rust the docker image uses?

1) cloned https://github.com/hyperledger-labs/solang 
then I did: 


![Screen Shot 2021-05-26 at 10 55 58 AM](https://user-images.githubusercontent.com/57117207/119708393-f68b2380-be10-11eb-8261-468bcb61dc27.png)

**Comment by seanyoung** [comment]
Would you mind trying `docker builder prune -a` and then trying again?

I must admit I'm not sure what is happening here. I've updated to the latest docker here and I am not seeing this issue.

**Comment by VadneyK** [comment]
Thanks! I did:
1) docker builder prune -a
2) git clean -fdx
3) docker image build .

and I got

![Screen Shot 2021-05-27 at 3 37 10 PM](https://user-images.githubusercontent.com/57117207/119905583-6973c780-bf01-11eb-912a-bdd7285b32bb.png)


At this point is this due to me having some faulty network or my docker set up is wrong? It is a different dependency that doesn't compile but it is really odd.

**Comment by seanyoung** [comment]
Thanks for trying that.

So the images used are for intel, not arm64. This is what docker has to say about it https://docs.docker.com/docker-for-mac/apple-silicon/

So assume you have rosetta2 installed already; also since this is quite new, docker should really be the latest and greatest.

Ideally there should arm64 images for you to use. I don't have arm64 hardware here. (Well, an raspberry pi!)

It might be possible to build them yourself and see if that helps. I'm not sure how you tell docker to build arm64 images, although I image this is the default.

```
docker build -t hyperledgerlabs/solang:ci -f scripts/ci.dockerfile
```

And once that is complete, try the above `docker image build .` again.

**Comment by seanyoung** [comment]
Sorry I forgot about this issue. You need to add a dot:
```
docker build -t hyperledgerlabs/solang:ci -f scripts/ci.dockerfile  .
```

**Comment by seanyoung** [comment]
So I have some arm64 hardware now, so I've pushed a new hyperledgerlabs/solang:ci image with both linux/arm64 and linux/amd64.

This means you can build on mac m1 without emulation, simply do `docker build .` in the solang directory and it should work fine.
