### ISSUE TITLE
no entry found for key

### ISSUE THREAD

**Issue by usd-yamazaki** [hyperledger-labs/solang#426]
When I compile the following code, I get a "no entry found for key" error.
The code has a minimal configuration that causes errors.
No matter which compilation target you choose, you will get the same error.
Replacing uint in the code with another type will result in the same error.

```
contract Test {
    using TestLib for TestLib.data;

    TestLib.data libdata;

    function contfunc(uint num) public {
        libdata.libfunc(num);
    }
}

library TestLib {
    using TestLib for TestLib.data;

    struct pair {
        uint a;
        uint b;
    }

    struct data {
        mapping(uint => pair) pairmap;
    }

    function libfunc(data storage self, uint value) internal {
        self.pairmap[self.pairmap[value].a].a = 1;
        self.pairmap[self.pairmap[value].b].b = 2;
    }
}
```

Is there any workaround?
Thank you.

**Comment by usd-yamazaki** [comment]
I'm sorry, I forgot to give the detailed error message.

> thread 'main' panicked at 'no entry found for key', src/codegen/dead_storage.rs:680:25
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by usd-yamazaki** [comment]
I was able to avoid the error by using the "--no-dead-storage" option.
But it raises a new error.
This seems to happen if there is mapping inside the structure.

> thread 'main' panicked at 'internal error: entered unreachable code', src/abi/substrate.rs:528:37
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by seanyoung** [comment]
Thank you very much for your detailed bug report. I've created #427 to solve the second issue. I am still working on `--no-dead-storage` problem.

Thank you again.

**Comment by usd-yamazaki** [comment]
Thank you for your prompt response.
#427 solved the second problem.
However, when I was trying other code, I got a similar error elsewhere.

```
contract Test {
    uint length = 1;

    function contfunc() public view returns (uint[] memory) {
        uint[] memory values = new uint[](uint(length));
        return values;
    }
}
```

> thread 'main' panicked at 'internal error: entered unreachable code', src/emit/mod.rs:1957:17
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by seanyoung** [comment]
@usd-yamazaki thank you very much for another great bug report. 

The length argument for a memory area was not handled correctly when it was specified from storage. This was not tested and not working. I have fixed this issue in pr #427. I still have to fix the dead storage problem.

Thank you!

**Comment by seanyoung** [comment]
@usd-yamazaki I've fixed the deadstorage issue in #428 

Thanks for your bug reports. Please let me know if you find any other issues.

**Comment by usd-yamazaki** [comment]
Thank you, the error is gone! Excellent work!

The point I was interested in is that the length of the dynamic array is uint32.
solidity probably has no array size limit. (That is, I think the upper limit is uint256)
Is this due to solang restrictions?
Realistically, we don't need such a huge array, so I think it's okay if you specify it in the document.

**Comment by seanyoung** [comment]
@usd-yamazaki you are right, you can use any type with ethereum solidity. However, this is a memory array, So, you cannot allocate a memory array of 2^32 elements in ethereum solidity, the contract does not have that much memory available to it.

In wasm memory is 32 bit so this works best. However, solang could accept `uint` and then check if it can be downcast to `uint32` without truncating the value.

**Comment by usd-yamazaki** [comment]
I understand, thank you!
