### ISSUE TITLE
ContractName.sol: error: no valid contracts found

### ISSUE THREAD

**Issue by Leon-Africa** [hyperledger-labs/solang#431]
Hi there Sean,

Thanks for the great project.

I setup solang on my pc in a few ways.

First using docker - this resulted in error: 

````ContractName.sol: error: no valid contracts found````

I then moved on to installing the solang release from crates.io - after successful install running  `

````solang --target anytarget ContractName.sol```` also results in error:  

````ContractName.sol: error: no valid contracts found````

I'm on Windows installed via cmd - added llvm to path.

What causes this error to occur?
Where is it located in the solang source code?

**Comment by seanyoung** [comment]
@Leon-Africa what's in your `ContractName.sol` file? If the file is empty, this error is expected.

**Comment by seanyoung** [comment]
Please re-open with more information if there still is an issue.
