### ISSUE TITLE
I feel I still need the metadata.json and wasm files.

### ISSUE THREAD

**Issue by usd-yamazaki** [hyperledger-labs/solang#443]
The file output by #344 has been changed from .wasm and .json to .contract.
This is nice if you use @polkadot/apps (https://github.com/polkadot-js/apps).
However, @polkadot/api and py-substrate-interface still require .wasm and .json.

Could you change it to create three files, .wasm, .json and .contract? (Or optionally)

Thank you.

reference
https://polkadot.js.org/docs/api-contract/start/code
https://polkascan.github.io/py-substrate-interface/contracts.html#substrateinterface.contracts.ContractCode.create_from_contract_files

**Comment by seanyoung** [comment]
I am not opposed to this change, this is a good idea.

This api-contract example uses the single .contract file: https://github.com/hyperledger-labs/solang/blob/main/integration/substrate/index.ts#L25

Also note that the metadata json and .contract file are the same, except the .contract also contains the wasm as a hexadecimal string.

**Comment by usd-yamazaki** [comment]
thank you.
The metadata will rewrite the contract file.
