### ISSUE TITLE
An error will occur if the same modifier is attached to one function more than once.

### ISSUE THREAD

**Issue by usd-yamazaki** [hyperledger-labs/solang#452]
As the title says.

Sample code
```
contract Test {
    modifier notZero(uint num) {
        require(num != 0, "invalid number");
        _;
    }

    function contfunc(uint num1, uint num2) public notZero(num1) notZero(num2) {
        // any code
    }
}
```

Errors that occur
> thread 'main' panicked at 'assertion failed: `(left == right)`
>   left: `Some(FunctionValue { name: "sol::Test::modifier::contfunc__uint256_uint256::notZero__uint256", address: 0x555558e48748, is_const: true, is_null: false, llvm_value: "declare internal i32 @\"sol::Test::modifier::contfunc__uint256_uint256::notZero__uint256\"(i256, i256)\n", llvm_type: "i32 (i256, i256)" })`,
>  right: `None`', src/emit/mod.rs:4365:17

Probably since the change of #447.

thank you.

**Comment by seanyoung** [comment]
You are right, this is broken. There is no test case for this either. I will look into this.

**Comment by seanyoung** [comment]
This should be resolved, thank you very much for your great bug report.
