### ISSUE TITLE
--target solana: How can I call a payable function with 'SOL value' from external account.

### ISSUE THREAD

**Issue by tunghm0812** [hyperledger-labs/solang#459]
In Solana, the transactions haven't the value fields. It only includes account_keys, programId, and data. So I don't know how to transfer SOL to the contract by the payable function and how to get msg.value in the transaction.

I don't find any document mention to the above issue or any example for the payable function. Please help me find out it. Thank you.

**Comment by seanyoung** [comment]
value transfers are missing from the Solana target. This is the last major feature gap. I'll be working on this shortly

**Comment by seanyoung** [comment]
Fixed by https://github.com/hyperledger-labs/solang/pull/542
