### ISSUE TITLE
Non-deterministic compiler output

### ISSUE THREAD

**Issue by scnale** [hyperledger-labs/solang#487]
Hey, I was trying out the compiler with this [prototype](https://github.com/seanyoung/uniswap-v2-core/tree/solana/solana) but I noticed that the compiler sometimes outputs a slightly smaller binary. I've been able to reproduce this with the following compilation parameters:

```sh
solang ../contracts/*.sol ../contracts/test/ERC20.sol --target solana -v
```
I trimmed down the compiled contracts to see if I could still reproduce this too:
```sh
solang ../contracts/test/ERC20.sol --target solana -v
```
And, indeed, I managed to obtain two significantly different builds for both parameters.

These smaller binaries happen to fail one of the [ERC20 tests](https://github.com/seanyoung/uniswap-v2-core/blob/4abaf4ee901e04852746ff8a48c9d516038ccdcb/solana/ers20.spec.ts#L71). I've been looking at the ELFs generated but all I notice about the smaller binaries is that they seem to have a few symbols less. Any ideas on what could be causing this? I'm using the compiler version 0.18 for linux.

**Comment by seanyoung** [comment]
That is very weird! I'm having a look.

**Comment by seanyoung** [comment]
I've found an issue which is fixed in #490. I should go back and see if the ERC20 tests are now consistent.

**Comment by seanyoung** [comment]
Ok, so there still is non-determinism in the tests.

**Comment by seanyoung** [comment]
The compiler output is deterministic now.
