### ISSUE TITLE
Why does Solang compile a constant into a function in the intermediate LLVM bitcode?

### ISSUE THREAD

**Issue by taquangtrung** [hyperledger-labs/solang#548]
Hi,

I'm studying the way that Solang compiles Solidity smart contracts into LLVM bitcode. When testing Solang to generate LLVM bitcode, I notice that a constant will be compiled into a function.

Here is the Solidity contract that I tested:

```solidity
pragma solidity ^0.4.19;

contract CountInput {
    uint public count = 1;

    function run(uint256 input) public {
        count += input;
    }
}
```

After running `solang --emit llvm-bc -v --target ewasm count_input.sol` and disassembling the output file `CountInput_deploy.bc` into `CountIput_deploy.ll`, I notice that there are two functions `CountInput::CountInput::function::count` and `CountInput::CountInput::function::run__uint256`.

```llvm
define internal i32 @"CountInput::CountInput::function::count"(i256* %0) {
entry:
  %slot = alloca i256, align 8
  store i256 0, i256* %slot, align 8
  %buf = alloca i8, i32 32, align 1
  %1 = bitcast i256* %slot to i8*
  call void @storageLoad(i8* %1, i8* %buf)
  %2 = bitcast i8* %buf to i256*
  %loaded_int = load i256, i256* %2, align 8
  store i256 %loaded_int, i256* %0, align 8
  ret i32 0
}

define internal i32 @"CountInput::CountInput::function::run__uint256"(i256 %0) {
entry:
  %1 = alloca i256, align 8
  %slot = alloca i256, align 8
  store i256 0, i256* %slot, align 8
  %buf = alloca i8, i32 32, align 1
  %2 = bitcast i256* %slot to i8*
  call void @storageLoad(i8* %2, i8* %buf)
  %3 = bitcast i8* %buf to i256*
  %loaded_int = load i256, i256* %3, align 8
  %4 = add i256 %loaded_int, %0
  %slot1 = alloca i256, align 8
  store i256 0, i256* %slot1, align 8
  store i256 %4, i256* %1, align 8
  %5 = bitcast i256* %slot1 to i8*
  %6 = bitcast i256* %1 to i8*
  call void @storageStore(i8* %5, i8* %6)
  ret i32 0
}
```

Are they the compiled code of `uint public count` and `function run(uint256 input)` in the original contract?

If yes, why the constant `count` is compiled into the function `CountInput::CountInput::function::count`?

I also noticed that there is another output file `CountInput_runtime.bc`, which does not contain the above two functions. Is `CountInput_runtime.bc` an optimized version of `CountInput_deploy.bc` where the above two functions are inlined?

Thank you very much for taking a look at my questions!

**Comment by seanyoung** [comment]
Since the variable `count` is declared `public`, it will have an accessor function. This means you can call count on the contract, and the value of count will be returned. This is why there is a function for this. You will see a function "count" in the abi file as well.

If you do not want the variable to have an accessor function, declare it `private` or `internal` rather than `public`.

The value of `count` can change so it is not constant. It is possible to declare a variable constant:

```
contract CountInput {
    uint public constant count = 1;
}
```
Now the function looks like:
```
define internal i32 @"CountInput::CountInput::function::count"(i256* %0) #16 {
entry:
  store i256 1, i256* %0, align 8
  ret i32 0
}
```

Does this answer your question?

**Comment by seanyoung** [comment]
For ewasm, there is the deploy code which is called during deployment, this contains the constructor and any functions that are called (they're all included, but will be removed by dead code elimination). The deploy code sets the address with the runtime code, so the deployer contains a copy of the runtime. Hope that makes sense. Ethereum is a bit odd in this area.

**Comment by taquangtrung** [comment]
@seanyoung: Thanks a lot for your reply! Now I understand why there is a function `count` in the compiled output.

For the runtime bitcode, is it correct to say that `CountInput_runtime.bc` is an optimized version of `CountInput_deploy.bc`?

**Comment by seanyoung** [comment]
When a contract is created on ethereum, the following steps are done:
- A create contract transaction is sent which contains a set of ewasm/evm instructions; this contains the ewasm version of `CountInput_deploy.bc` (the *deployer*) and the argument to constructor amongst other parameters
- A new address is for the new contract
- The deployer instructions are executed, and (if successful) the deployer returns the code which should be stored at the address (it returns the *runtime*)
- The return value of the deployer is stored at the new address
- From a Solang/llvm perspective, the runtime must be carried as a payload in the deployer; you'll see that in the deploy llvm ir there is:
```
@runtime_code = internal unnamed_addr constant [1627 x i8] c"\00asm\01\00...
```

Note that newer chains like Solana and Substrate do not have this deployer/runtime madness.

**Comment by taquangtrung** [comment]
@seanyoung : Wow, thank you very much for the explanation! Now I understand why there are two generated bitcode files!

**Comment by seanyoung** [comment]
np!
