### ISSUE TITLE
Maybe an incorrect warning related to the use of private variable?

### ISSUE THREAD

**Issue by taquangtrung** [hyperledger-labs/solang#551]
Hi,

When compiling the contract:

```solidity
pragma solidity ^0.4.19;

contract CountInput {
    uint private count = 1;

    function run(uint256 input) public {
        count += input;
    }
}
```

using the command `solang --emit llvm-bc -v --target ewasm count_input_private.sol`,
I receive a warning that: `warning: storage variable 'count' has been assigned, but never read`. 

Can you double check if this warning is incorrect? 

The variable `count` is used inside the function `run`.

Here is the full compilation output.

```sh
info: Solang version v0.1.9
~/count_input_private.sol:1:8-24: debug: pragma ‘solidity’ is ignored
Line 1:
	pragma solidity ^0.4.19;
	-------^^^^^^^^^^^^^^^^
~/count_input_private.sol:2:1-3:21: debug: found contract ‘CountInput’
Line 2:
	contract CountInput {
	^^^^^^^^^^^^^^^^^^^^
~/count_input_private.sol:4:5-27: warning: storage variable 'count' has been assigned, but never read
Line 4:
	uint private count = 1;
	^^^^^^^^^^^^^^^^^^^^^^
info: Generating LLVM IR for contract CountInput with target ewasm
info: Saving deploy LLVM BC ./CountInput_deploy.bc for contract CountInput
info: Saving runtime LLVM BC ./CountInput_runtime.bc for contract CountInput
```

Thanks!

**Comment by taquangtrung** [comment]
I think that `count += input` includes both a read and a write action to `count`, it is a shorthand for `count = count + input`.

So, the new message `warning: storage variable 'count' is written, but is never read` will still be confusing.

Btw, when I change `uint private count = 1;` to `uint public count = 1;`, then such message doesn't appear.

So, maybe it's something related to the `private` scoping?

**Comment by seanyoung** [comment]
Yes, the `+=` does need to read the value to increment it, but that's not the point: the actual value of count is still not used anywhere, It is just wasted space.

However if the `count` is declared `public` then the value can be read via the public accessor function, so it can be read. That's why the warning goes away when its declared `public`.

**Comment by taquangtrung** [comment]
Oh I see. I got your point here. It's like a more advanced heuristic to detect unused code!

Thank you for the explanation!

**Comment by seanyoung** [comment]
Glad I could help.

I think the compiler warning could be improved. Any suggests to what it should say?

**Comment by LucasSte** [comment]
Something like `Dead variable: Removing it will have no effect in your contract.` may be better. What do you think?

**Comment by taquangtrung** [comment]
Hi, to follow up with this example, when I change the statement `count += input` into `count = count + input`: 

```solang
// count_input2.sol
pragma solidity ^0.4.19;

contract CountInput {
  uint private count = 1;

  function run(uint256 input) public {
    count = count + input;
  }
}
```

Then Solang will not throw any warning:

```sh
solang --no-constant-folding --no-strength-reduce --no-dead-storage --no-vector-to-slice --emit llvm-bc -O none count_input2.sol --target ewasm

# No warning is printed.
```

Maybe Solang has a different treatment for `+=`?

**Comment by taquangtrung** [comment]
Also, when compiling the original example without optimization `--no-constant-folding --no-strength-reduce --no-dead-storage --no-vector-to-slice -O none`, I see that somehow the LLVM bitcode is still optimized:

```solidity
// count_input1.sol
pragma solidity ^0.4.19;

contract CountInput {
    uint private count = 1;

    function run(uint256 input) public {
        count += input;
    }
}
```

Here is the compilation command:

```sh
solang --no-constant-folding --no-strength-reduce --no-dead-storage --no-vector-to-slice --emit llvm-bc -O none count_input1.sol --target ewasm
```

and the generated bitcode of the function `run`:

``` llvm
define internal i32 @"CountInput::CountInput::function::run__uint256"(i256 %0) {
entry:
  ret i32 0
}
```

Can you advise how to totally disable the optimization pass of Solang?

Thank you!

**Comment by LucasSte** [comment]
> Hi, to follow up with this example, when I change the statement `count += input` into `count = count + input`:
> 
> ```solidity
> // count_input2.sol
> pragma solidity ^0.4.19;
> 
> contract CountInput {
>   uint private count = 1;
> 
>   function run(uint256 input) public {
>     count = count + input;
>   }
> }
> ```
> 
> Then Solang will not throw any warning:
> 
> ```shell
> solang --no-constant-folding --no-strength-reduce --no-dead-storage --no-vector-to-slice --emit llvm-bc -O none count_input2.sol --target ewasm
> 
> # No warning is printed.
> ```
> 
> Maybe Solang has a different treatment for `+=`?

Yes, "+=" and addition are different expressions in Solang. Currently, it verifies unused variables during an AST traversal and detecting that for complex assignments required special treatment, so it is a feature that will be added in the future.

**Comment by taquangtrung** [comment]
@LucasSte: do you think if it makes sense to disable this unused variable removal when the flag `-O none` (no optimization) is enabled?

Currently, even when `-O none` is enabled, this `count += input` statement will still be removed when generating LLVM bitcode.

I found the code that checks this unused condition at: https://github.com/hyperledger-labs/solang/blob/e3237e97a9b50b6c1ab0e61689c1e5e34150ca10/src/codegen/unused_variable.rs#L17

I can create a PR to disable this check when `-O none` is turned on.

**Comment by LucasSte** [comment]
There are two levels of optimization that happens in Solang. There is some optimization from Solang itself and those of LLVM. I have worked on some compiler optimizations for Solang and I can answer a few of your questions. For LLVM optimizations, you should ask @seanyoung.

You can try checking if commenting that function will work for your use case by running Solang with `--emit cfg`, which prints the CFG (Control Flow Graph) Solang generates and forwards to LLVM. If you see your variables in the Solang's CFG, but not in LLVM bitcode, that's an LLVM optmization happening.

The function you highlighted do remove unused variables and all their assignments throughout the code, but it does not control the LLVM optimizations. Test you modifications with `--emit cfg` and compare it with the generated LLVM bitcode. 

Feel free to write a PR for the `-0 none`. That is a nice adding.

**Comment by seanyoung** [comment]
I think everything in this issue has been addressed. Can it be closed?

**Comment by taquangtrung** [comment]
Yes, thank you! I'll close it! :)
