### ISSUE TITLE
Language Server ignore imports

### ISSUE THREAD

**Issue by ChristianChiarulli** [hyperledger-labs/solang#554]
Is there anyway you can provide a comment that will allow the language server to ignore certain errors.

![image](https://user-images.githubusercontent.com/29136904/141049280-ef30bcd3-eaf2-4af2-92fd-36ef0336295a.png)

Something like:

```
// ignore file not found error
import "hardhat/console.sol";
```

**Comment by seanyoung** [comment]
The language server goes through the normal parser code from the compiler. 

Why would you would want suppress this error?

You could also use the vscode ui to filter errors.

**Comment by ChristianChiarulli** [comment]
Whenever I import something remote I will see this error.

I would like to suppress it because it's annoying.

Also this is Neovim, so I don't have that option.

**Comment by seanyoung** [comment]
I think a better solution might be to figure out a way to solve the import errors. I'm not keen on suppressing some errors because they're annoying - they are real issues that likely to cause further issues, since some definitions are missing. We might need some extra functionality to make imports work better.

So, in the example above, you import `hardhat/console.log`. Is this file available somewhere? What directory are you run neovim? Are you in the hardhat directory already? Does the error go away if you run neovim in the directory that contains `hardhat/console.log`?

**Comment by ChristianChiarulli** [comment]
The error will go away if the file is locally available. However,

![image](https://user-images.githubusercontent.com/29136904/142140385-7188c7f4-6855-47d8-af1f-4bfaef8d4319.png)

![image](https://user-images.githubusercontent.com/29136904/142140450-fceb9720-3408-4a74-803a-e3a3ea79d010.png)

These sources are fetched at compile time, using brownie for instance.

**Comment by seanyoung** [comment]
I think you are right, a package manager would help here. That does not exist yet, and that would be a major piece of work.

The entries under `compiler.solc.remappings` could be provided as command line arguments to solang, like so:

```
solang --importmap=@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2
```

**Comment by beauwilliams** [comment]
> Is there anyway you can provide a comment that will allow the language server to ignore certain errors.
> 
> ![image](https://user-images.githubusercontent.com/29136904/141049280-ef30bcd3-eaf2-4af2-92fd-36ef0336295a.png)
> 
> Something like:
> 
> ```
> // ignore file not found error
> import "hardhat/console.sol";
> ```

Adding an import map to the neovim lsp config for solang should fix it.

You can do it like so by adding an argument to the default `cmd` specified in neovim/lspconfig

`cmd = {"solang", "--language-server", "--target", "ewasm" , "--importmap=hardhat=node_modules/hardhat" }`

[see my full neovim lsp config for solang here](https://github.com/beauwilliams/Dotfiles/blob/master/Vim/nvim/lua/lsp/_solang.lua)
