### ISSUE TITLE
Zero initialized mappings do not work for Solana target

### ISSUE THREAD

**Issue by sushi-shi** [hyperledger-labs/solang#559]
This contract fails when target is `Solana` and compiles on `Substrate`.
```solidity
contract FixedSwap {

    struct A {
        mapping(uint256 => uint256) a;
    }

    A[] private a;

    function boom() private {
        a.push();
    }

}
```
With
```console
thread 'main' panicked at 'internal error: entered unreachable code', src/emit/mod.rs:5936:41
```

**Comment by sushi-shi** [comment]
There is even smaller error case. Still fails for Solidity.
```solidity
contract FixedSwap {

    mapping(uint256 => uint256)[] private foo;

    function boom() private {
        foo.push();
    }

}
```

**Comment by ivancsicsmarkus** [comment]
I think the issue is that function boom() is private and it is not used at all in the FixedSwap contract.

**Comment by seanyoung** [comment]
> I think the issue is that function boom() is private and it is not used at all in the FixedSwap contract.

That should not make the compiler panic. I'm working on a solution in #580 .
