### ISSUE TITLE
solang --target solana deploy only success in local network

### ISSUE THREAD

**Issue by BSix5** [hyperledger-labs/solang#568]
The compiled program runs normally on the solana local network, but runs on other clusters with errors. The error message is as follows: 

Transaction simulation failed: Error processing Instruction 1: Program failed to complete 
    Program 11111111111111111111111111111111 invoke [1]
    Program 11111111111111111111111111111111 success
    Program 5XFgqZgRXCNqqZ76aBVnu3amYWSG8fceEYxxxviWid6c invoke [1]
    Program 5XFgqZgRXCNqqZ76aBVnu3amYWSG8fceEYxxxviWid6c consumed 2573 of 200000 compute units
    Program failed to complete: ELF error: Unresolved symbol (sol_log_data) at instruction #2401 (ELF file offset 0x4a20)
    Program 5XFgqZgRXCNqqZ76aBVnu3amYWSG8fceEYxxxviWid6c failed: Program failed to complete
(node:13096) UnhandledPromiseRejectionWarning: Error: Program failed to complete
    at parseSimulationError (E:\project_qh\PlantNftServer\solana\node_modules\@solana\solidity\lib\logs.js:161:31)
    at E:\project_qh\PlantNftServer\solana\node_modules\@solana\solidity\lib\logs.js:123:27
    at Generator.throw (<anonymous>)
    at rejected (E:\project_qh\PlantNftServer\solana\node_modules\@solana\solidity\lib\logs.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by seanyoung** [comment]
This means that the `sol_log_data` syscall is not enabled. This syscall is a feature that may require enabling. What cluster are you using? How was it set up?

**Comment by BSix5** [comment]
> This means that the `sol_log_data` syscall is not enabled. This syscall is a feature that may require enabling. What cluster are you using? How was it set up?

i use https://api.devnet.solana.com cluster

**Comment by BSix5** [comment]
> > This means that the `sol_log_data` syscall is not enabled. This syscall is a feature that may require enabling. What cluster are you using? How was it set up?
> 
> i use https://api.devnet.solana.com cluster

https://github.com/hyperledger-labs/solang/commit/e9e0ba5a5621ab2939051c11c53b3a3a3daa62f8
i see you add sol_log_data in syscalls, Do you need to recompile solang by yourself
