### ISSUE TITLE
Can Solang generate debugging information of variable, function names and locations?

### ISSUE THREAD

**Issue by taquangtrung** [hyperledger-labs/solang#584]
Hi,

I'm looking for the mapping for variable names/locations from Solidity source code to the generated LLVM bitcode. Is it possible to make Solang generate such debugging information?

For example, here is a Solidity source code:

``` solidity
// integer_overflow_mul.sol
pragma solidity ^0.4.19;

contract IntegerOverflowMul {
    uint public count = 2;

    function run(uint256 input) public {
        // <yes> <report> ARITHMETIC
        count *= input;
    }
}

```

When compiling to LLVM IR by `solang integer_overflow_mul.sol -O none --target ewasm --emit llvm-ir`, the generated metadata doesn't contain any information about variables like `count`, `input`, etc.. 

Can you advise how to make Solang generate such information?

FYI, below are what were generated by Solang, and there is no information about variable, function names... 

``` llvm
!0 = !{!"clang version 12.0.1 (https://github.com/solana-labs/llvm-project 747454b0ae556da120b9ad1645a13e48c40601a6)"}
!1 = !{!"clang version 11.0.1 (git://github.com/llvm/llvm-project 13e4369c73355a6c5a31fc1a1115fc7c69743ada)"}
!2 = !{!"clang version 11.0.1 (git://github.com/llvm/llvm-project 852f4d8eb6d317be0947055c0bb6b4fd6c9aa930)"}
!3 = !{i32 1, !"wchar_size", i32 4}
!4 = !{!5, !5, i64 0}
!5 = !{!"long long", !6, i64 0}
!6 = !{!"omnipotent char", !7, i64 0}
!7 = !{!"Simple C/C++ TBAA"}
!8 = distinct !{!8, !9}
!9 = !{!"llvm.loop.mustprogress"}
!10 = !{!6, !6, i64 0}
!11 = distinct !{!11, !9}
!12 = distinct !{!12, !9}
!13 = distinct !{!13, !9}
!14 = distinct !{!14, !9}
!15 = distinct !{!15, !9}
!16 = distinct !{!16, !9}
!17 = distinct !{!17, !9}
!18 = distinct !{!18, !9}
!19 = !{!20, !20, i64 0}
!20 = !{!"int", !6, i64 0}
!21 = distinct !{!21, !9}
!22 = distinct !{!22, !9}
!23 = !{!24, !26, i64 12}
!24 = !{!"chunk", !25, i64 0, !25, i64 4, !26, i64 8, !26, i64 12}
!25 = !{!"any pointer", !6, i64 0}
!26 = !{!"long", !6, i64 0}
!27 = !{!24, !26, i64 8}
!28 = !{!24, !25, i64 0}
!29 = !{!24, !25, i64 4}
!30 = distinct !{!30, !9}
!31 = distinct !{!31, !9}
!32 = distinct !{!32, !9}
!33 = !{!34, !34, i64 0}
!34 = !{!"__int128", !6, i64 0}
!35 = !{!36, !36, i64 0}
!36 = !{!"_ExtInt(256)", !6, i64 0}
!37 = !{!38, !38, i64 0}
!38 = !{!"_ExtInt(512)", !6, i64 0}
```

**Comment by seanyoung** [comment]
solang needs to add the correct debug information. This should be done using this api https://thedan64.github.io/inkwell/inkwell/debug_info/index.html

All the information should be known by solang, it just needs wiring up.

**Comment by taquangtrung** [comment]
@seanyoung: I can help to implement this feature. 

Can you give me some suggestions on the starting points so that I can get into it quicker?

**Comment by seanyoung** [comment]
@taquangtrung sorry for the delay I had to get up to speed with debug info too.

Solang generates the llvm IR in `src/emit/mod.rs`. There is a struct called `Binary` which holds all the relevant information for generated binary file (this could do with a better name).

First creating the debug info builder needs to be created, like this https://thedan64.github.io/inkwell/inkwell/debug_info/index.html#setting-up-the-module-for-holding-debug-info . This should be done in `Binary::new()`, here https://github.com/hyperledger-labs/solang/blob/main/src/emit/mod.rs#L5401

Now `binary.emit_functions()` will generate llvm IR for all the functions. Here, for each function (which will arrive the emit modules a CFG), extra debug information needs to be provided like so: https://thedan64.github.io/inkwell/inkwell/debug_info/index.html#creating-function-debug-info

The llvm type for a local varibles/storage variable is created in `fn llvm_type()`. https://github.com/hyperledger-labs/solang/blob/main/src/emit/mod.rs#L5914 This will have to amended with debug info.

There is also line information, which will need to be added for each CFG instruction: https://github.com/hyperledger-labs/solang/blob/main/src/emit/mod.rs#L3092. However, the CFG does not contain location information so this is more work: codegen will need to add this. I'm not sure if you need this.

Let me know how you get on! Thanks.

**Comment by taquangtrung** [comment]
Hi @seanyoung, I'm sorry for being inactive over the last month. Now, I finally can find some time to work on this issue.

Ideally, I want to make Solang be able to generate enough debugging information similar to what Clang does.

Here is an example of debugging information of a variable generated by Clang,
which captures detailed information of the variable's name, scope, file name,
line number, type:

```
!20 = !DILocalVariable(name: "source", scope: !21, file: !1, line: 28, type: !22)

;; where

!1 = !DIFile(filename: "CWE121_Stack_Based_Buffer_Overflow__CWE131_memcpy_01.c", directory: "/home/trungtq/workspace/sv-comp/juliet/CWE121_Stack_Based_Buffer_Overflow/s01")
!21 = distinct !DILexicalBlock(scope: !13, file: !1, line: 27, column: 5)
!22 = !DICompositeType(tag: DW_TAG_array_type, baseType: !5, size: 320, elements: !23)
```

I saw from https://github.com/hyperledger-labs/solang/blob/2a69dbe797231e1c04976ab31e659ac130e3a5e2/src/sema/ast.rs#L1168 that location (maybe line number) is already captured?

Also, from
https://github.com/hyperledger-labs/solang/blob/2a69dbe797231e1c04976ab31e659ac130e3a5e2/src/sema/ast.rs#L317 that maybe variable's name and type are also tracked?

If I'm not wrong, I will not need to attach new information to the AST, just need to utilize the existing one to generate the debugging information?

Can you advise if my understanding is correct?

Thanks for your help!

**Comment by seanyoung** [comment]
> Hi @seanyoung, I'm sorry for being inactive over the last month. Now, I finally can find some time to work on this issue.
> 
> Ideally, I want to make Solang be able to generate enough debugging information similar to what Clang does.
> 
> Here is an example of debugging information of a variable generated by Clang, which captures detailed information of the variable's name, scope, file name, line number, type:
> 
> ```
> !20 = !DILocalVariable(name: "source", scope: !21, file: !1, line: 28, type: !22)
> 
> ;; where
> 
> !1 = !DIFile(filename: "CWE121_Stack_Based_Buffer_Overflow__CWE131_memcpy_01.c", directory: "/home/trungtq/workspace/sv-comp/juliet/CWE121_Stack_Based_Buffer_Overflow/s01")
> !21 = distinct !DILexicalBlock(scope: !13, file: !1, line: 27, column: 5)
> !22 = !DICompositeType(tag: DW_TAG_array_type, baseType: !5, size: 320, elements: !23)
> ```
> 
> I saw from
> 
> https://github.com/hyperledger-labs/solang/blob/2a69dbe797231e1c04976ab31e659ac130e3a5e2/src/sema/ast.rs#L1168
> that location (maybe line number) is already captured?

Yes, exactly. Now `Loc` is an enum which can be either `Builtin` or `File(usize, usize, usize)`. The first `usize` is an index into the `files` array from `Namespace`, which will give you the full path and other bits of information. The second usize is the byte offset where the location starts and the last/third usize is the byte offset where the location ends.  

You can convert the byte offset to line number/column number with `ns.files[file_no].offset_to_line_column(offset)`.

> 
> Also, from
> 
> https://github.com/hyperledger-labs/solang/blob/2a69dbe797231e1c04976ab31e659ac130e3a5e2/src/sema/ast.rs#L317
> that maybe variable's name and type are also tracked?

In the control flow graph there is a variable table for each function. This will give the name and location of each variable that exists in a function. https://github.com/hyperledger-labs/solang/blob/main/src/codegen/cfg.rs#L328

> If I'm not wrong, I will not need to attach new information to the AST, just need to utilize the existing one to generate the debugging information?

When a file is compiled, it first parsed and converted to an AST. This will give the full parse tree with all symbols resolved. This is used by the language server for example.

The AST is then converted into a CFG (control flow graph) which contains instructions rather than solidity code statements. See https://github.com/hyperledger-labs/solang/blob/main/src/codegen/cfg.rs#L322-L335 
Everything you need for debugging information should be there.

> Can you advise if my understanding is correct?

Please let me know if I can help in any way! Sorry for taking so long to respond, I aim to be better next time.

**Comment by taquangtrung** [comment]
Thanks @seanyoung for the suggestion! I have been working on this issue recently. Your suggestions are very helpful. I'll try to create a draft PR in the next few days.

**Comment by thanhtoantnt** [comment]
Hi @seanyoung. I am working on this task. Thanks to your suggestions, I am able to `DISubprogram` debug information to each function. Currently, I am working on how to add debug location information `DILocation` to instructions. 

My idea is to find the location of each instruction. For example, I can get the location of `Instr::Set { expr, .. }` using `expr.loc()`. Then, I use `ns.files[file_offset].offset_to_line_column(offset);` to find the line and column numbers of the location. Currently, I am able to add debug location to most of the instructions.

However, some instructions have the location of `Codegen`. Hence, we cannot get the debug location. Do you have any suggestions in this case? 

Feel free to correct me if my understanding and/or implementation are not correct.

**Comment by thanhtoantnt** [comment]
Hi @seanyoung. To give you more context, we are testing this simple contract.
```
contract flipper {
	bool private value;

	constructor(bool initvalue) {
		value = initvalue;
	}

	function flip() public {
		value = !value;
	}

	function get() public view returns (bool) {
		return value;
	}
}
```
The debug location of the function `get` is as follows.
```
define internal i32 @"flipper::flipper::function::get"(i1* %0) !dbg !70 {
entry:
  %slot = alloca i256, align 8
  store i256 0, i256* %slot, align 8
  %buf = alloca i8, i32 32, align 1
  %1 = bitcast i256* %slot to i8*
  call void @storageLoad(i8* %1, i8* %buf)
  %2 = bitcast i8* %buf to i1*
  %loaded_int = load i1, i1* %2, align 1
  store i1 %loaded_int, i1* %0, align 1, !dbg !72
  ret i32 0, !dbg !72
}
```
where:
```
!70 = distinct !DISubprogram(name: "flipper::flipper::function::get", linkageName: "flipper::flipper::function::get", scope: null, file: !3, type: !58, flags: DIFlagPublic, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !2, retainedNodes: !71)
!72 = !DILocation(line: 17, column: 2, scope: !70)
```
So, there are some instructions without debugging locations. Do you think it is because they are generated by the compiler or we can get debugging locations in other ways?
Thanks.

**Comment by seanyoung** [comment]
@taquangtrung thanks for working on this.

What's happening here is that you're using the locations stored in the CFG. solang only uses these locations for a few flow based diagnostics, so they're not well tested or maintained. As you noticed, `Instr` enum does not even have locations for most. This is just a plain oversight.

So locations can be added wherever they are needed, that's not a problem. Probably were you are coming across `Loc::Codegen`, this can be replaced with a more useful location in the source code. These locations just haven't been used at all before, this is why they're so poor (untested means broken, after all).

What specific locations are you missing? And where are you coming across `Loc::Codegen`?

**Comment by thanhtoantnt** [comment]
@seanyoung thanks for your reply.
Here is the `Instr` instruction that has the `Loc::Codegen` in function `flip`:
```
function: flipper::flipper::function::flip
instr: LoadStorage { res: 3, ty: Bool, storage: NumberLiteral(Codegen, Uint(256), 0) } - Codegen
```
Regarding other functions in this simple contract, I notice that another `LoadStorage` instruction also has the `Loc::Codegen` info in the `get` function.
```
function: flipper::flipper::function::get
instr: LoadStorage { res: 5, ty: Bool, storage: NumberLiteral(Codegen, Uint(256), 0) } - Codegen
````
Do you have any suggestions as to where I can add the `loc` information to `Instr` instructions that currently use `Loc::Codegen`?

**Comment by thanhtoantnt** [comment]
@seanyoung. I have a look at `codegen`, and currently, I am able to generate the debug location for most of the `Instr` instructions. We just have one small issue with `Instr::Return` because it doesn't have the `loc` field. When the `value` field is not empty, I can use the `loc` of `value[0]` as the `loc` of `Instr::Return`. 

But when the `value` field is empty, we cannot generate the debug information. Also, I notice that the generated return statement does not relate to the source Solidity code since the Solidity program doesn't contain a return statement.

For example, in the `flipper` example (https://github.com/hyperledger-labs/solang/blob/main/examples/flipper.sol), the generated LLVM code for function `flip` is as follows.
```
define internal i32 @"flipper::flipper::function::flip"() !dbg !64 {
entry:
  %0 = alloca i1, align 1, !dbg !68
  %slot = alloca i256, align 8, !dbg !68
  store i256 0, i256* %slot, align 8, !dbg !68
  %buf = alloca i8, i32 32, align 1, !dbg !68
  %1 = bitcast i256* %slot to i8*, !dbg !68
  call void @storageLoad(i8* %1, i8* %buf), !dbg !68
  %2 = bitcast i8* %buf to i1*, !dbg !68
  %loaded_int = load i1, i1* %2, align 1, !dbg !68
  %3 = icmp eq i1 %loaded_int, false, !dbg !69
  %slot1 = alloca i256, align 8, !dbg !70
  store i256 0, i256* %slot1, align 8, !dbg !70
  store i1 %3, i1* %0, align 1, !dbg !68
  %value = alloca i256, align 8, !dbg !68
  %value8 = bitcast i256* %value to i8*, !dbg !68
  call void @__bzero8(i8* %value8, i32 4), !dbg !68
  %value2 = load i1, i1* %0, align 1, !dbg !68
  %4 = bitcast i256* %value to i1*, !dbg !68
  store i1 %value2, i1* %4, align 1, !dbg !68
  %5 = bitcast i256* %slot1 to i8*, !dbg !68
  call void @storageStore(i8* %5, i8* %value8), !dbg !68
  ret i32 0
}
```

We cannot generate the debug location for the last instruction since `flip` does not have a return statement. However, we expect all instrucitons to have a debug location.
