### ISSUE TITLE
Can't deploy to devnet: Unresolved symbol (sol_log_data)

### ISSUE THREAD

**Issue by ivancsicsmarkus** [hyperledger-labs/solang#589]
I can't deploy to [devnet](https://docs.solana.com/cluster/rpc-endpoints#devnet). I'm using the latest solang, built from Github directly with the [latest llvm](https://github.com/hyperledger-labs/solang/releases/tag/llvm13.0-1) released. 

I've seen [this](https://github.com/hyperledger-labs/solang/issues/568) issue but I don't know how it got resolved. Building from source did not help me. I'm using an M1 Mac.

```
TransactionError: Program failed to complete
    at parseTransactionError (/Users/username/Documents/Git/projectname/node_modules/@solana/solidity/lib/logs.js:161:31)
    at /Users/username/Documents/Git/projectname/node_modules/@solana/solidity/lib/logs.js:123:27
    at Generator.throw (<anonymous>)
    at rejected (/Users/username/Documents/Git/projectname/node_modules/@solana/solidity/lib/logs.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  logs: [
    'Program 11111111111111111111111111111111 invoke [1]',
    'Program 11111111111111111111111111111111 success',
    'Program 9dimaeTWpxwTQcQHMruKaUJmn15bN5322qgD91x6VxkM invoke [1]',
    'Program 9dimaeTWpxwTQcQHMruKaUJmn15bN5322qgD91x6VxkM consumed 1939 of 200000 compute units',
    'Program failed to complete: ELF error: Unresolved symbol (sol_log_data) at instruction #8199 (ELF file offset 0xff50)',
    'Program 9dimaeTWpxwTQcQHMruKaUJmn15bN5322qgD91x6VxkM failed: Program failed to complete'
  ],
  computeUnitsUsed: 1939
}
```

**Comment by ivancsicsmarkus** [comment]
[solang.zip](https://github.com/hyperledger-labs/solang/files/7655879/solang.zip)
Here's solang executable built for ARM Mac that produces faulty build of contract.

**Comment by ivancsicsmarkus** [comment]
I've found the issue. I was using standard Solidity libs from Openzeppelin. Specifically [Ownable](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/Ownable.sol). It was emitting events in the constructor. For some reason, this caused issues. Commenting `emit OwnershipTransferred(oldOwner, newOwner);` fixed the error. I think I'll have to port some of these contracts so that they work properly with Solang.

I'm not sure why this fixes the issue as there is this test in the JS lib that passes: https://github.com/solana-labs/solana-solidity.js/blob/master/test/examples/events/contracts/Events.sol

Does anybody know what's wrong here?

**Comment by seanyoung** [comment]
The problem is that the `sol_log_data` syscall is not enabled on devnet. In the mean time, you can run up a private solana node and develop against that.

**Comment by ivancsicsmarkus** [comment]
Thank you for your answer.

What about sol_set_return_data? I've got some errors for that as well, that I could not resolve yet.

**Comment by seanyoung** [comment]
The same issue. We should be activating all the features on testnet soon.

**Comment by seanyoung** [comment]
All the features are enabled on testnet (not devnet!) now.

**Comment by Abubakar672** [comment]
Can we deploy the contract of solang on mainnet of solana ?

**Comment by seanyoung** [comment]
@Abubakar672 not yet, we're waiting for the features to stabilize on testnet/devnet (i.e. see more testing). I'm sure in a month or two those features will be enabled

**Comment by Abubakar672** [comment]
sounds great thanks @seanyoung

**Comment by springrainroni** [comment]
When i try to connect the network on testnet it shows on airdrop "429 Too Many Requests:  {"jsonrpc":"2.0","error":{"code": 429, "message":"Too many requests from your IP, contact your app developer or support@rpcpool.com."}, "id": "2d037c66-c515-4b67-ac37-5f832622313d" }" and 
when i try to connect on devnet it shows error "Transaction was not confirmed in 30.01 seconds. It is unknown if it succeeded or failed. Check signature 4DBYAh3UdkteB4sCza4cHGTNzjsEVSFsn7s6rtYpn2PhyP6Pbiuyg9GkNJ481jzxMQkqsCD9mBtCzLxxkJtg5iB using the Solana Explorer or CLI tools.
    at Connection.confirmTransaction"

**Comment by seanyoung** [comment]
Solana devnet is having problems, this should be resolved soon. Please check solana discord #devnet-announcements
