### ISSUE TITLE
Receive and transfer Solana SPL token into smart contract

### ISSUE THREAD

**Issue by 0xS0l** [hyperledger-labs/solang#607]
I'm building a smart contract that can receive and send Solana SPL tokens, but I don't see any document mention about that or any example from doing that.

Have Solang supported that yet? If it is, please help me find it out. Thank you.

**Comment by seanyoung** [comment]
This is not possible yet. I am working on this

**Comment by 0xS0l** [comment]
Thanks. May I ask the ETA for that feature if you don't mind?

**Comment by seanyoung** [comment]
I'm drawing up some plans now, there is quite a bit of plumbing involved. I think it should be done by the end of January.

**Comment by seanyoung** [comment]
I think three parts are needed:
- [x] Implement `.writeUint16LE()` and friends on `bytes` so we can encode the spl input
- [ ] Make the accounts accessible so that we can extract the total supply via `tx.accounts[]` builtin
- [ ] Make it possible to specify the accounts on a call

**Comment by DanBokhari98** [comment]
Is this still within your end of January Timeline? Thank you :)

**Comment by seanyoung** [comment]
@DanBokhari98 some other issues came up with the parser. I'm afraid it will take a little longer.

Having said that, large parts have been implemented now. We need a method for passing in accounts to a CPI call. With that in place, all the spl-token glue code can be written.

Done by the end of Feb, promise :)

**Comment by javamr123** [comment]
> @DanBokhari98 some other issues came up with the parser. I'm afraid it will take a little longer.
> 
> Having said that, large parts have been implemented now. We need a method for passing in accounts to a CPI call. With that in place, all the spl-token glue code can be written.
> 
> Done by the end of Feb, promise :)

Has it been completed？

**Comment by seanyoung** [comment]
> Has it been completed？

I am afraid not! :grimacing: All the new syntax is in place, but there is an issue where the array of accounts that needs to be passed into the CPI call is an array of pointers to structs, not just a plain array of structs. This is some difficult rework, which I've been working on here https://github.com/hyperledger-labs/solang/pull/685

The spl-token is top priority and I'm not working on anything else.
