### ISSUE TITLE
Installation error for MacOS M1

### ISSUE THREAD

**Issue by abhi3700** [hyperledger-labs/solang#611]
I am facing an installation error related to `solang`.

```console
Compiling contract-metadata v0.3.0
   Compiling tower-lsp v0.14.1
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "-arch" "x86_64" "/Users/abhi3700/solang/target/release/deps/solang-1427980f513fa9cf.solang.8ada8e5f-cgu.0.rcgu.o" "-L" "/Users/abhi3700/s

= note: ld: in /var/folders/cw/dc7mkcsd6yx76lscv6w1hpcw0000gn/T/rustcfY2S0N/libllvm_sys-061409e80b7aca55.rlib(Core.cpp.o), archive member 'Core.cpp.o' with length 361336 is not mach-o or llvm bitcode for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I followed these from [here](https://solang.readthedocs.io/en/latest/installing.html):
* Install LLVM from [here](https://solang.readthedocs.io/en/latest/installing.html#installing-llvm-on-mac)
* Install solang from __crates.io__ using `$ cargo install solang`.

What could be the reason?
Anyone please?

**Comment by seanyoung** [comment]
So you're on mac m1,which is arm hardware. Somehow your rust is linking with `"cc" "-m64" "-arch" "x86_64"` which intel.

Could you post the output of `rustup show` please?

You downloaded the llvm for mac m1, right?

**Comment by abhi3700** [comment]
I installed the LLVM for Mac M1.

This is the result of `rustup show`:
```
❯ rustup show                                                                 ⏎
Default host: x86_64-apple-darwin
rustup home:  /Users/abhi3700/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin
bpf
1.52.1-x86_64-apple-darwin
1.56.1-x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.56.1 (59eed8a2a 2021-11-01)
```

**Comment by seanyoung** [comment]
You've installed rust for x86-64 (intel), not arm.
