### ISSUE TITLE
Multiline DocComments don't preserve newlines

### ISSUE THREAD

**Issue by shekhirin** [hyperledger-labs/solang#620]
Source code:
```solidity
/// @title Multiline
/// name
/** @author Alexey
Shekhirin */
contract Contract {}
```

Parse Tree generated from `solang::parser::parse()` function:
```rust
SourceUnit([
    ContractDefinition(ContractDefinition {
        doc: [
            DocComment { offset: 0, tag: "title", value: "Multiline name" },
            DocComment { offset: 0, tag: "author", value: "Alexey Shekhirin" }
        ],
        loc: Loc(1, 62, 80),
        ty: Contract(Loc(1, 62, 70)),
        name: Identifier {
            loc: Loc(1, 71, 79),
            name: "Contract"
        },
        base: [],
        parts: []
    })
])
```

Expected Parse Tree:
```rust
...
        doc: [
            DocComment { offset: 0, tag: "title", value: "Multiline\nname" },
            DocComment { offset: 0, tag: "author", value: "Alexey\nShekhirin" }
        ],
...
```

---

Also not sure whether it's already possible or not but it would be cool to differentiate `///` from `/** ... */` for NatSpec comments.

**Comment by mattsse** [comment]
that info seems to be available on the Token level
https://github.com/hyperledger-labs/solang/blob/1b231dc6986868d9c54af879bb40853bf6d9aa44/solang-parser/src/lexer.rs#L183-L184
but omitted here when the ast type `DocComment` is created:
https://github.com/hyperledger-labs/solang/blob/1b231dc6986868d9c54af879bb40853bf6d9aa44/solang-parser/src/doc.rs#L33
I also suspect that's where comments can be merged and newlines are lost?

I think adding a `r#type: CommenType` field to `DocComment` will fix it.
