### ISSUE TITLE
Error "Assertion `NumBits >= MIN_INT_BITS && "bitwidth too small'" failed" when compiling a smart contract

### ISSUE THREAD

**Issue by taquangtrung** [hyperledger-labs/solang#623]
Hi,

When compiling the following contract using this command:

```solidity
// contract name:  incorrect_constructor_name3.sol
pragma solidity ^0.8.11;

contract Missing{
    address payable private owner;

    modifier onlyowner {
        require(msg.sender==owner);
        _;
    }

    function Constructor()
        public
    {
        owner = payable(msg.sender);
    }

    receive () external payable {}

    function withdraw()
        public
        onlyowner
    {
        owner.transfer(payable(this).balance);
    }

}
```

using the command `solang incorrect_constructor_name3.sol --emit llvm-bc --target ewasm`, I encountered this error:

``` sh
solang: /home/runner/work/solang/solang/llvm-project/llvm/lib/IR/Type.cpp:276: static llvm::IntegerType* llvm::IntegerType::get(llvm::LLVMContext&, unsigned int): Assertion `NumBits >= MIN_INT_BITS && "bitwidth too small"' failed.
Aborted (core dumped)
```

Can you advise how to make Solang to compile it successfully?

(FYI, I can compile this contract normally with Solidity compiler (Solc) version 0.8.11)

Thanks!

**Comment by seanyoung** [comment]
Looks like this is an issue introduced by https://github.com/hyperledger-labs/solang/pull/322

I'm looking at it now

**Comment by taquangtrung** [comment]
@seanyoung: Thank you for the quick fix! Solang can compile that contract perfectly now!
