### ISSUE TITLE
Support parsing regular comments

### ISSUE THREAD

**Issue by shekhirin** [hyperledger-labs/solang#625]
Currently, only NatSpec comments are parsed into `DocComments`.

To be able to fully reconstruct the code from Parse Tree, we need to add support for regular comments (both line `//` and block `/* */`) to grammar and other places.

**Comment by gakonst** [comment]
+1 would be v useful to have that, the PR linked above is a code formatter which needs to preserve doc comments even if they're not natspec

**Comment by seanyoung** [comment]
I get it. I'm not sure how easy it is to add comments to the parse tree of an LR(1) parser, since they can occur almost anywhere.

Let me see what I can dig up

**Comment by seanyoung** [comment]
I think the grammar will need entries everywhere where comments are permitted. This will be hard to do without making the grammar ambiguous.

**Comment by seanyoung** [comment]
Implemented in #656
