### ISSUE TITLE
Support array slice operator

### ISSUE THREAD

**Issue by shekhirin** [hyperledger-labs/solang#626]
Currently, `solang` can only parse subscript on arrays (e.g. `arr[0]`) without an ability to take a slice.

Slices were [added](https://blog.soliditylang.org/2020/05/26/array-slices/) in Solidity 0.6.0 and have several forms:
- `arr[2:5]`
- `arr[2:]`
- `arr[:5]`
- `arr[:]`

**Comment by seanyoung** [comment]
Yes, this feature is missing.
