### ISSUE TITLE
Support to convert ".sol" file to solana using Docker

### ISSUE THREAD

**Issue by graphmyworkatgit** [hyperledger-labs/solang#668]
I am working on Solang (docker container installed) on windows machine,  as per instructions  provided in below link.

https://solang.readthedocs.io/en/latest/running.html#running-solang-using-container

solang from Docker works fine:

![image](https://user-images.githubusercontent.com/78626677/154184978-b8d0c475-329d-4450-9634-5a7d9b705d5d.png)

then to generate files, I used below command 

docker run --rm -it -v C:\Repository\solang2:/sources ghcr.io/hyperledger-labs/solang --target solana -o /sources /sources/HelloWorld.sol

**absolute path in windows:**  C:\Repository\solang2\sources

![image](https://user-images.githubusercontent.com/78626677/154184720-9b575f40-b737-4123-897c-2a4d79bd01dd.png)

 I keep getting below error. 

![image](https://user-images.githubusercontent.com/78626677/154184804-e6d978b7-e0b8-4d0b-a006-d2aa42691841.png)

```
C:\Users\alpha>docker run --rm -it -v C:\Repository\solang2:/sources ghcr.io/hyperledger-labs/solang --target solana -o /sources /sources/flipper.sol
error: file not found ‘/sources/flipper.sol’
```

can someone help me what mistake am doing.

**Comment by seanyoung** [comment]
I think you should be doing:

```
C:\Users\alpha>docker run --rm -it -v C:\Repository\solang2\sources:/sources ghcr.io/hyperledger-labs/solang --target solana -o /sources /sources/flipper.sol
error: file not found ‘/sources/flipper.sol’
```

**Comment by graphmyworkatgit** [comment]
thanks

> I think you should be doing:
> 
> ```
> C:\Users\alpha>docker run --rm -it -v C:\Repository\solang2\sources:/sources ghcr.io/hyperledger-labs/solang --target solana -o /sources /sources/flipper.sol
> error: file not found ‘/sources/flipper.sol’
> ```

Thanks a ton.! it worked! I am glad to connect with you!
