### ISSUE TITLE
Unable to deploy filesl flipper.abi & bundle.so generated using solang to solana network

### ISSUE THREAD

**Issue by BlockchainDeveloper009** [hyperledger-labs/solang#672]
As per the instruction, i compiled 'flipper.sol' using solang and that generated 'flipper.abi' & 'bundle.so' files. Then I created flipper.js file 

https://solang.readthedocs.io/en/latest/targets.html

am facing below error: 

![image](https://user-images.githubusercontent.com/97905727/154367889-1554eae4-e6db-42e1-8ea4-e38a08534d33.png)

Project files(bundle.so,flipper.abi) generated using solang(conainer) and .sol & .js files I created based on the documentation provided in solang github.

![image](https://user-images.githubusercontent.com/97905727/154368025-004f47dd-cae8-4dd7-8065-1c9c254eea10.png)

can anyone help me to resolve this issue. please.

my discord:  gtrharish#6309
mytwitter: harrypks19

**Comment by seanyoung** [comment]
You need run up a solana node to connect to.
```
docker run --rm -it -p 8899:8899 -p 8900:8900 solanalabs/solana:v1.9.6
```
