### ISSUE TITLE
Unable to call `.send` within a loop while targeting Solana

### ISSUE THREAD

**Issue by rzmay** [hyperledger-labs/solang#675]
I'm building a Solana program to manage payments to multiple accounts, however the compiler fails whenever a `.send()` call is made within a loop. For example, the following code compiles just fine:
```solidity
function send( address[3] memory receivers ) external payable {
    require(payable(receivers[0]).send(uint64(5)), "Transaction failed");
}
```
But the following code throws an error:
```solidity
function send( address[3] memory receivers ) external payable {
    for (uint i = 0; i < receivers.length; i++) {
      require(payable(receivers[i]).send(uint64(5)), "Transaction failed");
    }
}
```
`LLVM ERROR: Unsupported dynamic stack allocation`

I've also tried using `.transfer()` and `.call()`, all throw the same error. Is this behavior unsupported or is there a way I can resolve this issue?

**Comment by seanyoung** [comment]
This is an issue with code generation

**Comment by seanyoung** [comment]
I can't reproduce this issue on solang latest. What version are you using? `solang --version`

**Comment by rzmay** [comment]
This appears to only be an issue with the cargo version of solang -- I rebuilt the executable from the git repository, and not only did this build display a version number correctly (`solang version v0.1.9-143-g56047c4`) but it also compiled the program with no issues. My problem is resolved for now, I'll leave this issue open in case the cargo release needs to be investigated. Feel free to close if not. Thank you!

**Comment by seanyoung** [comment]
The cargo version is also v0.1.9 so this will also have the same problem. 

Thanks for using solang
