### ISSUE TITLE
How to use "--import-path" with "--language-server"?

### ISSUE THREAD

**Issue by aj3423** [hyperledger-labs/solang#705]
I'm using solang with Neovim, succeeded to get it work with normal diagnostic. But how to import other contracts?

My contract uses openzeppelin like:
```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";   // <------ diagnostic shows "file not found..."
// ...
```
My command line: `solang --language-server --target solana -I /e/sol/node_modules`,  and the file does exist in "/e/sol/node_modules/@openzeppelin/...".

What do I miss?

**Comment by seanyoung** [comment]
I think there is  a  bug in solang. I am not sure it uses the `--import` command line option at all in the language server. I'll get back to you.
