### ISSUE TITLE
publish solang-parser 0.1.11

### ISSUE THREAD

**Issue by mattsse** [hyperledger-labs/solang#724]
the latest patch is not published on crates.io.

could you please publish it?

Thanks!

**Comment by seanyoung** [comment]
of course, let me do that now!

How are you getting on with the formatter? Is there somewhere we can follow/help with your work?

**Comment by mattsse** [comment]
Thanks!

wip here https://github.com/gakonst/foundry/pull/889
but not the highest priority atm but aiming to finish this in the upcoming weeks.

the trickiest part will probably formatting comments, not quite sure how to handle them yet

**Comment by seanyoung** [comment]
published
