### ISSUE TITLE
Cannot find local function when creating state variable.

### ISSUE THREAD

**Issue by LucasSte** [hyperledger-labs/solang#762]
When creating a function pointer variable as an attribute of a contract, I can assign it a function of the contract itself. For instance, the following contract does so and works in solc.

```solidity
contract testing {
    
    function testPtr(int a) public pure returns (int) {
        return a/2;
    }

    function(int) external pure returns (int) sfPtr = this.testPtr;

    function doTest() public pure {
        assembly {
            let x := 1
        }
    }
}
```

However, Solang raises the following error:
```
contract ‘testing’ has no public function ‘testPtr’
```

**Comment by seanyoung** [comment]
The order in which functions/variables are resolved is broken. The variables are resolved before functions, so when we resolve the initializer the function `testPtr` does not exist yet.

It gets more complicated:
```
contract b {
    function testPtr(int a) public pure returns (int) {
        return a/2;
    }
}

contract testing is b {
    function(int) external pure returns (int) sfPtr = this.testPtr;
}
```
