### ISSUE TITLE
Error message for "now" is wrong

### ISSUE THREAD

**Issue by LucasSte** [hyperledger-labs/solang#779]
In this contract, 
```solidity
contract test {
      event LockRecord(address,uint,uint256); 
      function foo() public {
          emit LockRecord(address(this), now, 34);
      }
}
```

I get this error: `'now' is not found`, however I should be given instructions to change `now` to `block.timestamp`.

**Comment by seanyoung** [comment]
The emit code should resolve its arguments with `ResolveTo::Type(ty)` with the correct `Type`. Currently it does not do that.
