### ISSUE TITLE
assembly memory-safe not parsed

### ISSUE THREAD

**Issue by seanyoung** [hyperledger-labs/solang#828]
```
function f() pure {
    assembly "evmasm" ("memory-safe") {}
}
```
Found in #787

**Comment by cameel** [comment]
Note that currently there's also a Natspec annotation that has the same effect:
```solidity
/// @solidity memory-safe-assembly
assembly {
    ...
}
```
Though it's just a temporary solution for backwards compatibility and in the long term it will be removed.

See [Memory safety](https://docs.soliditylang.org/en/latest/assembly.html?highlight=memory-safe#memory-safety).
