### ISSUE TITLE
We should not give up resolving imports

### ISSUE THREAD

**Issue by LucasSte** [hyperledger-labs/solang#830]
Solang gives up resolving imports if one of them fails. When we build [this contract](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol) from OpenZepellin, Solang fails on `Address.sol` and does not even parse `Context.sol`. This creates inconsistent error messages when we try to resolve the main file.

**Comment by seanyoung** [comment]
We can change the code to continue importing even if a previous import had an error.

The same file might be imported twice, and we should not produce duplicate errors for the same file.
