### ISSUE TITLE
compatible solidity 0.8

### ISSUE THREAD

**Issue by z79422957** [hyperledger-labs/solang#847]
Hi,
When will solang be compatible with solidity 0.8? Are there any rules here? Thank you!

**Comment by seanyoung** [comment]
Actually, I think all the functionality for 0.8 is there. There are some gaps like some yul builtins, but these are not 0.8 specific.

**Comment by seanyoung** [comment]
@z79422957 is there a specific reason you are asking for this?

**Comment by z79422957** [comment]
Oh, thanks, I am a novice of solang. I want to use solang to make Solana, but my previous sol files was solidity version 0.8. 
I have another question. When I export wasm or BPF file, how should I deploy it later? Thank you

**Comment by seanyoung** [comment]
The documentation is updated to reflect that solang is now compatible with 0.8.

To deploy the contract, please the `@solana/solidity` npm package, see 
https://github.com/solana-labs/solana-solidity.js/
