### ISSUE TITLE
inline assembly is not yet supported

### ISSUE THREAD

**Issue by mouseless-eth** [hyperledger-labs/solang#852]
Using solang as an LSP for my neovim set up. Getting an error around my assembly block in one of `.sol` contracts. Is there any way to suppress this message? I want to import my contract (the one containing the assembly block) in another contract but solang does not recognize the import because of this one warning/error.

**Error Message** : inline assembly is not yet supported

Example of the assembly block in solidity contract that is causing me issues
```solidity
function hasHEVMContext() internal view returns (bool) {
    uint256 hevmCodeSize = 0;
    assembly {
        hevmCodeSize := extcodesize(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D)
     }
     return hevmCodeSize > 0;
}

```

**Comment by mouseless-eth** [comment]
Rebuilt my solang executable using `LucasSte:yul-cfg-expression`'s branch but looks like there is still no support for the `extcodesize` opcode

**Comment by seanyoung** [comment]
@mouseless-eth what are you using solang language server for? solang does not have support for `extcodesize` yet.

Where do you intend to run your compiled contracts? evm ethereum or one the solang targets?

**Comment by mouseless-eth** [comment]
I am using the solang language server in conjunction with [neovim's built in LSP plugin](https://github.com/neovim/nvim-lspconfig) for error checking, completions, format checking, ... 

I am targeting the ethereum EVM by using the command `solang --language-server --target ewasm`

**Comment by seanyoung** [comment]
Adding support for `extcodesize` isn't that hard, it just means wiring it up to the [getExternalCodeSize](https://github.com/ewasm/design/blob/master/eth_interface.md#getexternalcodesize) syscall. However, I am not sure if this a good long term solution, because there will be other syscalls which may not be so easy to implement.
