### ISSUE TITLE
Generating an executable function/contract from EVM bytecode?

### ISSUE THREAD

**Issue by drewstone** [hyperledger-labs/solang#858]
Is it possible to pass raw bytecode into the Solang compiler and outgoing a WASM blob that can be executed in a standard rust program?

We have a Solidity smart contract that we've created using raw EVM assembly. We'd like to execute a function on this contract in Rust. The thinking is to first compile this contract into eWASM using Solang and then somehow execute it in Rust (in a WASM sandboxed environment).

Any information is helpful!

**Comment by seanyoung** [comment]
solang itself does not know anything about EVM, so this is currently not possible using solang. This is not something we're planning to do.

I think there is an evm to wasm converter, see #658
