### ISSUE TITLE
The Mac pre-compiled binary does not work

### ISSUE THREAD

**Issue by LucasSte** [hyperledger-labs/solang#883]
If we download the pre-compiled binary for Mac, MacOS does not allow us to run it.

```
"solang" can't be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.
```

**Comment by seanyoung** [comment]
mac/intel? which version of macos?

**Comment by LucasSte** [comment]
MacOS 12.2 using ARM. I believe that this is something Apple enforces on all computers. I can try myself when I arrive home.

**Comment by seanyoung** [comment]
Have you followed the instructions? https://solang.readthedocs.io/en/latest/installing.html#download-release-binaries:

On MacOS, remember to remove the quarantine attribute using xattr -d com.apple.quarantine solang-mac-arm in the terminal.

**Comment by LucasSte** [comment]
> On MacOS, remember to remove the quarantine attribute using `xattr -d com.apple.quarantine solang-mac-arm` in the terminal.

Yes, this totally solves the installation issue. I'll update the documentation to make it clear that this command is needed for both Intel and ARM Macs.

**Comment by LucasSte** [comment]
Updated documentation with #888.
