### ISSUE TITLE
When connected through docker on which port do i run local host.

### ISSUE THREAD

**Issue by OnahProsperity** [hyperledger-labs/solang#897]
Having issues for some days now running local host after connecting via docker, and deploying to testnet kept reverting due to block number even after I have used third party API (ANKR), so the question now is:
1. how to fix the block number timeout.
2. How to run local host with docker.

**Comment by seanyoung** [comment]
For the first issue, this most likely happens when uploading the `bundle.so` contract code. It is possible to use `solana program deploy -ut bundle.so` and the use the program account from the output.

For the second one, just run:
```
podman run --rm -it -p 8899:8899 -p 8900:8900 solanalabs/solana:v1.10.25
```
Replace `podman` with `docker` if you want to use docker.

Does that help?

**Comment by seanyoung** [comment]
> Thanks. wasn't really clear have been trying to sort it out with other means and it not just working as I expected, had to read the code directly from the install file and still, so I tried what you mentioned, `podman run --rm -it -p 8899:8899 -p 8900:8900 solanalabs/solana:v1.10.25` and changed `podman` to `docker` it open and was running docker forever and when tried it, still same. maybe if there is another way to help will appreciate it. If number one above works for me I won't need the number but maybe it will be helpful later for someone else, can you share more details on the number 1 answer you provided above?

I think I need some more details about what you are trying to do, my guessing isn't getting us anywhere. Can you please provide some steps please?

**Comment by OnahProsperity** [comment]
sure do that as soon as I get back.

**Comment by OnahProsperity** [comment]
so I have been interacting with the Solang using docker this way, `docker run --rm -it -v $(pwd):/sources ghcr.io/hyperledger-labs/solang solana --version` in other to get the version and currently running on version 
`solang version v0.1.12-13-g4dcdcdb8`
OS = attached
![image](https://user-images.githubusercontent.com/40717516/177365478-0711ab16-4373-44bf-a1cb-b5d73e48d575.png)

my flipper.js looks like this:
![image](https://user-images.githubusercontent.com/40717516/177368536-1a2522f0-fe13-4b97-9441-7e221f52bbe1.png)

and whenever I tried to run `node flipper.js` from the directory I get the `failed to send transaction: Transaction simulation failed: Blockhash not found` and if I use a public node like Ankr still gets a timeout error, the command that I used to generate the `bundle.so` seems not to figure it out for now but it looks like 
`docker run --rm -it -v $(pwd):/sources ghcr.io/hyperledger-labs/solang solana --target solana flipper.sol`

**Comment by OnahProsperity** [comment]
I hope with this information you have a clue of what I am talking about.
following this doc: [doc](https://soliditydeveloper.com/solana) and the [Solang](https://solang.readthedocs.io/en/latest/index.html) doc

**Comment by seanyoung** [comment]
If you want to connect to a local solana node, you need to change `testnet` to `http://localhost8899/`

**Comment by OnahProsperity** [comment]
yea sure, aware of that.
tried it and I got `FetchError: request to http://localhost:8899/ failed, reason: connect ECONNREFUSED 127.0.0.1:8899` that was why I was looking forward to try connecting to dev net.
