### ISSUE TITLE
Vectors make Solana's mock VM fail

### ISSUE THREAD

**Issue by LucasSte** [hyperledger-labs/solang#926]
The following contract stems an error in our Solana's mock VM: `Err(AccessViolation(6740, Load, 18897868827, 4, "input"))`.

```solidity
        contract Testing {

        struct NonConstantStruct {
            uint64 a;
            string[] b;
        }

        string[] vec_2;
        NonConstantStruct[] complex_array;
        function addData2() public {
            vec_2.push("tea");
            vec_2.push("coffee");
            NonConstantStruct memory ss = NonConstantStruct(897, vec_2);
            complex_array.push(ss);

            vec_2.pop();
            vec_2.pop();
            vec_2.push("cortado");
            vec_2.push("cappuccino");
            NonConstantStruct memory sr = NonConstantStruct(74123, vec_2);
            complex_array.push(sr);
        }
    }
```

**Comment by LucasSte** [comment]
Fixed by #928

**Comment by Subway2023** [comment]
@LucasSte May I ask how you executed this program in SVM. Should we use rbpf's command to pass parameters or anchor

**Comment by LucasSte** [comment]
Solang has a mock VM in the test folder, which we used for this case. The usage is limited to internal testing. If your intentions are user facing tests, I do not recommend it.

**Comment by Subway2023** [comment]
@LucasSte My interest is making a fuzz tool. But I don't know how to efficiently execute the Solana contract. I tried anchor test as a fuzzy, but it is too slow. You need to deploy the contract on the node and call it. May I ask if there is a more efficient testing method.
