### ISSUE TITLE
can I use llvm pass to analyze the emit bc file?

### ISSUE THREAD

**Issue by system-pclub** [hyperledger-labs/solang#962]
Hello, can I write an LLVM pass to analyze the emit bc file? I try to build an LLVM pass based on the released solang-llvm, but I received many "Undefined symbols for architecture x86_64" complaints when compiling the pass. I am not sure whether I make some mistakes when configuring the pass or solang-llvm disables some functionalities in the original llvm.

**Comment by seanyoung** [comment]
Would you mind giving a bit more information on what you're doing exactly?

Are you building llvm with the x86_64 target?

The solang does not produce x86_64 llvm ir, it produces llvm ir for wasm or bpf. However, depending on what you're trying to do, it may just work.

**Comment by system-pclub** [comment]
yeah. we have figured out how to build the pass now. Thanks a lot for your response.

**Comment by system-pclub** [comment]
I have one more question. If I want to use solang to build a solidity project with multiple files (like https://github.com/transmissions11/solmate), how should we do that?

**Comment by seanyoung** [comment]
> I have one more question. If I want to use solang to build a solidity project with multiple files (like https://github.com/transmissions11/solmate), how should we do that?

Just add all the files and solang will generate code for each of them.

**Comment by system-pclub** [comment]
I see. Thanks a lot!
