### ISSUE TITLE
Errors when generating bitcode with -g

### ISSUE THREAD

**Issue by thanhtoantnt** [hyperledger-labs/solang#967]
When I add debug information (#949), I only tested it with `--emit llvm-ir`. Currently, I tested it with `emit llvm-bc` and got this error:
+ Command: `../solang compile flipper.sol -O none --target ewasm --emit llvm-bc -v -g`
+ Error message: 
```
solang: /home/runner/work/solang/solang/llvm-project/llvm/lib/Bitcode/Writer/BitcodeWriter.cpp:2157: void {anonymous}::ModuleBitcodeWriter::writeMetadataRecords(llvm::ArrayRef<const llvm::Metadata*>, llvm::SmallVectorImpl<long unsigned int>&, std::vector<unsigned int, std::allocator<unsigned int> >*, std::vector<long unsigned int, std::allocator<long unsigned int> >*): Assertion `N->isResolved() && "Expected forward references to be resolved"' failed.
Aborted (core dumped)
```
Do you have any suggestions on how I can fix it? I looked into `src/bin/solang.rs` but still not sure what cause this error.

**Comment by thanhtoantnt** [comment]
When I use `--emit llvm-ir`, I got this:
```
!79 = distinct !DISubprogram(name: "sol::flipper::storage_initializers", linkageName: "sol::flipper::storage_initializers", scope: null, file: !3, type: !75, flags: DIFlagPrivate, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !2, retainedNodes: !80)
!80 = <temporary!> !{}
```
When I look at the `llvm` code, I suspect that the field `retainedNodes` has a `temporary` value which causes this error. However, I cannot find any field to change this value. 

Do you have any idea about this problem?

**Comment by seanyoung** [comment]
I am perplexed by this issue. If I run:
```
$ solang compile examples/flipper.sol -O none --target ewasm --emit llvm-ir -v -g
```
Then the resulting llvm IR file is not valid, according to llc:
```
$ $ llc flipper_runtime.ll 
llc: error: llc: flipper_runtime.ll:3723:7: error: Expected '!' here
!61 = <temporary!> !{}
```
Now it looks like you're looking in the right direction, but I don't know how to resolve it

**Comment by thanhtoantnt** [comment]
@seanyoung I fixed it. I forgot to add `dibuilder.finalize();` at the end. I am testing it and will submit a PR soon. That's why I closed this issue.
